apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    type: bluedep
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
      app: nginx-app