apiVersion: v1
kind: Pod
metadata:
  name: rajapp-pod
  labels:
    app: rajapp
    type: front-end
spec:

  containers:
    - envFrom:
        - configMapRef:
            name: webapp-config-map
        - secretRef:
            name: webapp-secret-map
      name: rajcontainer
      image: rajaanova/raj:1.1.2